### ISSUE TITLE
Crear colección en servidor

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/stac-data-tools#10]
# Descripción

Implementar la lógica para continuar con la creación de la colección en el servidor. Se debe cumplir con lo siguiente:

- [x] Después de validar la colección, crear los cog, subirlos a azure y crear la colección completa en el servidor.
- [x] Si una colección con el mismo nombre o id existe, retornar un mensaje indicándolo y solicitando que se pase un parámetro para sobreecribirla. Crear este nuevo parámetros.
- [x] En caso de que se pase el parámetro para sobreescribir la colección, se debe borrar la colección existente en el servidor y crear una nueva.

# Consideraciones

- Recordar actualizar el readme de acuerdo a los parámetros y variables que se agreguen con esta implementación.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/stac-data-tools/10?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by ManuelStardust** [comment]
Logre avanzar con la lógica del proceso, sin embargo al momento de hacer las pruebas de conversion de TIF a COG como lo veniamos haciendo (con comandos directos del sistema) aparece un error de espacio disponible, no logre solucionarlo manteniendo el uso de las funciones que teniamos, pero encontre otra forma de hacerlo usando el paquete osgeo. Con esta libreria se reduce mucho el código, sin embargo estoy verificando que el resultado sea igual.

**Comment by ManuelStardust** [comment]
Se avanzo con los ajustes al PR sin embargo aún me quedan algunos por finalizar.
