### ISSUE TITLE
Actualizaciones en servidor STAC

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/stac-data-tools#12]
Las actualizaciones que se van a hacer en esta tarea son: Cambiar estructura de assets, limpiar colecciones en blobstorage y desplegar nueva versión del servidor

1. "Reinstalar" el servidor que se tiene corriendo en azure, desplegar el [nuevo proyecto](https://github.com/PEM-Humboldt/stac-fastapi) - Tener en cuenta borrar el contenedor de la base de datos para iniciar la instalación desde 0 - **Recordar** borrar las imágenes y el código viejo
1. Borrar todas las colecciones existentes en el storage de azure
1. Cambiar la implementación de la carga de colecciones para que dentro del storage de azure los raster queden agrupados por colección, de decir, como crear una carpeta por cada colección y dentro de esta los raster de todos los items.
1. Volver a cargar la colección `lossPersistence`, pero corregir los ids de los items para que sean los periodos, por ejemplo `2010-2015` y no `colombiapp_2010_2015`

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/stac-data-tools/12?planning-poker) with Zenhub @cazapatamar @denarch22

**Comment by erikasv** [comment]
@denarch22 @cazapatamar @ManuelStardust revisar de nuevo la descripción de la tarea para la estimación

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/stac-data-tools/12?planning-poker) with Zenhub @ManuelStardust

**Comment by cazapatamar** [comment]
Durante el sprint anterior estuve trabajando sobre esta tarea pero no pude tener un avance significativo por algunos inconvenientes que se me presentaron:

1. No pude desplegar stac-data-tools ya que presentaba un conflicto con la instalacion de GDAL ya que se estaban instalando con pip. Por eso se decidió en una tarea posterior crear el ambiente conda en el proyecto e instalar esta o otras dependencias desde conda-forge.
2. Tuve problemas para acceder e nuestros servicios en la cuenta de Azure. Pude iniciar sesión pero no me aparecia el directorio con todos los servicios. Hablé con Edwin para que me ayudara a revisar los permisos de mi usuario pero hasta el momento no he recibido respuesta.

**Comment by denarch22** [comment]
Durante el desarrollo de la tarea tuve algunos inconvenientes con las librerías, ya que el equipo estaba molestando en el ambiente virtual, igualmente con Docker, se realiza igualmente los ajustes mencionados en el PR, y con el nuevo equipo, se pudo probar tanto el cargue de una colección según las especificación de la tarea, así como el levantamiento del servidor stac.

**Comment by denarch22** [comment]
Se realizo ajustes en el código para mostrar los logs tanto en consola como en un archivo log, se agrego un comando para la eliminación de las colecciones dentro del código, t se ajusto para ejecutar por comandos por ejemplo la creación de una colección, se realizo el MR.
