### ISSUE TITLE
Crear ambiente de conda

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/stac-data-tools#13]
# Descripción

Crear un ambiente de conda como el que se creó para [regio](https://github.com/PEM-Humboldt/regi0/blob/master/environment.yml) o [biomodelos-db-utils](https://github.com/PEM-Humboldt/biomodelos-db-utils/blob/master/condaenv.yml) donde se asegure la instalación de gdal desde el binario (canal conda-forge) y no se intente compilar.

Mover todas las dependencias a este ambiente (eliminar el archivo requirements.txt al final) y actualizar las instrucciones de instalación.

Verificar que funcione en varios sistemas operativos (si es necesario instalar máquina virtual para la prueba).

Adicionalmente, si lo considera pertienente, documentar los pasos para crear este ambiente en un nuevo archivo de la carpeta `devprocess` (esto porque no tenemos claro el cómo hacerlo para esta tarea por ejemplo)

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/stac-data-tools/13?planning-poker) with Zenhub @cazapatamar

**Comment by cazapatamar** [comment]
Se dejan instrucciones para crear ambiente conda en proyectos python en este [archivo](https://docs.google.com/document/d/1PQOE35s5OkW3N5B9V5ql27__btKW6qyvl6vRvK7yG_w/edit)
