### ISSUE TITLE
[Spike] Organizar proyecto inicial

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/stac-data-tools#2]
# Descripción

Crear la estructura base del proyecto, definiendo lo siguiente:

- manejo de dependencias
- punto de entrada (cómo se ejecutaría el código para cargar los datos) y organización de los insumos
- otras herramientas que puedan ser útiles en el proyecto (por ejemplo cosas como el equivalente a eslint o nvm, que no necesariamente afectan el producto final)

# Consideraciones
Para el punto de entrada considerar todas las opciones que se desee, menos una interfaz gráfica 😅. Adicionalmente Victor mencionó que corren cosas en python desde R (usando reticulate), supongo que si lo pensamos como una librería también funcionaría, aunque no sé realmente la ventaja de esto, hay que evaluarlo.

Se define como spike porque se sugiere seguir buenas prácticas de la comunidad o lo que implementen otros proyectos grandes.

Resolver las discusiones del documento de proyecto de python al finalizar esta tarea, con las decisiones que se hayan tomado

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/stac-data-tools/2?planning-poker) with Zenhub @erikasv @ManuelStardust

**Comment by ManuelStardust** [comment]
Se alcanzaron a revisar algunas recomendaciones y mejores practicas para proyectos en Python.

- La guía de recomendaciones actual es la [PEP08](https://peps.python.org/pep-0008/).
- Se encontro que existe a libreria pyscaffold que ayuda a crear y estructurar proyectos en python
- Para el caso de manejo de estilos y erroes de código existen dos herrameintas Pylint y Flake8
