### ISSUE TITLE
Ajuste en cargue y propiedades de las colecciones

### ISSUE THREAD

**Issue by denarch22** [PEM-Humboldt/stac-data-tools#20]
Según el trabajo concentrado se identificaron 3 temas:

1. Es necesario revisar el código del cargue  de las colecciones ya que se esta presentando inconvenientes un las ultima capa.
2. Es necesario explorar la manera de colocar en las propiedades las categorías y valores de LossPersistence desde los metadatos de la colección en el stac, ya que actualmente están quemadas dentro del código del backend de biotableto.
3. Actualizar el readme de stac-data-tools con el nuevo funcionamiento con comandos

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/193?planning-poker) with Zenhub @cazapatamar @denarch22 @ManuelStardust @dev-juanzb-humboldt

**Comment by denarch22** [comment]
Se realizo los respectivos ajustes del readme y se verificó el error del cargue de la colección, al realizar pruebas locales se identifico que era temas del servidor de stac ya que no estaba actualizada a la versión del ambiente local y no permitía el cargue de la colección del año 2016-2021, por lo que se procedió a realizar la actualización del contenedor en el servidor de la nube, también se reviso en la reunión del día de ayer cual era la mejor manera de colocar los metadatos en la colección, que contuvieran valores, categorías y los colores para el raster, la cual se determino colocar en los items, ya que desde la colección por el estándar manejado en STAC no es posible.

**Comment by denarch22** [comment]
Se realizo el respectivo ajuste para el tema de la colección, según la ultima reunión, se identifico una manera de agregar las propiedades de classes,values, y colors con extra fields, se verifico y esta quedando en la colección en el nivel indicado.

**Comment by denarch22** [comment]
Se realiza el respectivo MR según las correcciones realizadas.
