### ISSUE TITLE
GitHub Actions y página de documentación

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/stac-data-tools#6]
# Descripción

Realizar las siguientes configuraciones en el repositorio de GitHub

- Workflow para que se ejecute la verificación de estilos con flake8 cuando se haga un PR a main
- Configuración de la página de documentación (para esto se puede basar en el repositorio del backend de biotablero)

Agregar al readme la información con la página de documentación (y si lo desea, la indicación/explicación de la verificación que se ejecutará en los PR)

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/stac-data-tools/6?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by ManuelStardust** [comment]
En la documentación de Pdoc se explica la forma de generar un workflow propio para las paginas de github [pdoc's GitHub Actions workflow](https://github.com/mitmproxy/pdoc/blob/main/.github/workflows/docs.yml), sin embargo no se implemento en esta tarea ya que toca entender un poco mas el contenido que debe tener el [script](https://github.com/mitmproxy/pdoc/blob/main/docs/make.py) para generar la documentación.
